# Build stage
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps --force
COPY . .

# Variables de entorno para el build
ARG REACT_APP_API_URL
ARG REACT_APP_USERS_SERVICE_URL
ARG REACT_APP_GAMIFICATION_URL
ARG REACT_APP_AI_SERVICE_URL
ARG REACT_APP_ENV=production
ARG REACT_APP_ENVIRONMENT=production
ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_USERS_SERVICE_URL=$REACT_APP_USERS_SERVICE_URL
ENV REACT_APP_GAMIFICATION_URL=$REACT_APP_GAMIFICATION_URL
ENV REACT_APP_AI_SERVICE_URL=$REACT_APP_AI_SERVICE_URL
ENV REACT_APP_ENV=$REACT_APP_ENV
ENV REACT_APP_ENVIRONMENT=$REACT_APP_ENVIRONMENT
ENV GENERATE_SOURCEMAP=false
RUN npm run build

# Production stage - usar serve para servir archivos estáticos
FROM node:18-alpine
WORKDIR /app
COPY --from=build /app/build ./build
RUN npm install -g serve
EXPOSE 8080
CMD ["serve", "-s", "build", "-l", "8080"] 