services:
  - type: web
    name: financial-resume-frontend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    buildArgs:
      - key: REACT_APP_API_URL
        value: https://financial-resume-monorepo-l71a.onrender.com/api/v1
      - key: REACT_APP_ENV
        value: production
      - key: REACT_APP_ENVIRONMENT
        value: production
    healthCheckPath: /
    plan: starter
    autoDeploy: true
