run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  govet:
    shadow: true
  errcheck:
    check-type-assertions: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
